"""Tests for T0.1 dynamic planner stage execution path."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from neuronium_agent.api import AgentRunner
from neuronium_agent.config import AppConfig, ProjectConfig, StorageConfig
from neuronium_agent.storage.fs_cas import FsCasStore
from neuronium_agent.storage.sqlite_store import SqliteIndexStore
from neuronium_agent.types import RunRequest


_PLANNED_GRAPH = {
    "metadata": {
        "plan_id": "plan-dynamic-generated-test",
        "description": "Generated by planner replay",
        "version": 1,
    },
    "nodes": [
        {
            "node_id": "read_000",
            "node_type": "mcp",
            "label": "Read source",
            "parameters": {
                "tool_name": "fs.read_text",
                "tool_args": {"path": "/tmp/a.md", "out_key": "doc_000"},
            },
            "priority": 0,
        },
        {
            "node_id": "merge_docs",
            "node_type": "aggregate",
            "label": "Merge documents",
            "parameters": {},
            "priority": 1,
        },
        {
            "node_id": "draft_report",
            "node_type": "model",
            "label": "Draft report",
            "parameters": {},
            "priority": 2,
        },
        {
            "node_id": "critic_report",
            "node_type": "model",
            "label": "Critic report",
            "parameters": {},
            "priority": 3,
        },
    ],
    "edges": [
        {"source": "read_000", "target": "merge_docs", "edge_type": "data", "label": ""},
        {"source": "merge_docs", "target": "draft_report", "edge_type": "data", "label": ""},
        {"source": "draft_report", "target": "critic_report", "edge_type": "data", "label": ""},
    ],
    "conditional_branches": [],
}


_REPLAY_MAP: dict[str, list[dict]] = {
    "plan_graph": [{
        "outputs": {
            "parsed": _PLANNED_GRAPH,
            "content": json.dumps(_PLANNED_GRAPH),
        },
        "quality_signals": {"tokens_used": 50},
    }],
    "read_000": [{
        "outputs": {
            "doc_000": "# Test doc\nDynamic planner stage",
            "doc_000__path": "/tmp/a.md",
        },
        "quality_signals": {},
        "status": "COMPLETED",
    }],
    "merge_docs": [{
        "outputs": {"doc_000": "# Test doc\nDynamic planner stage"},
        "quality_signals": {},
        "status": "COMPLETED",
    }],
    "draft_report": [{
        "outputs": {"content": "# Dynamic Report [doc_000]\n## Action items\n- OK"},
        "quality_signals": {"tokens_used": 20},
    }],
    "critic_report": [{
        "outputs": {
            "content": json.dumps({
                "verdict": "PASS",
                "confidence": 0.95,
                "evidence": ["doc_000 cited"],
                "gaps": [],
            }),
        },
        "quality_signals": {"tokens_used": 10},
    }],
}


def _make_runner(
    tmp_dir: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> AgentRunner:
    monkeypatch.setenv("NEURONIUM_OPENAI_API_KEY", "test-fake-key")

    config = AppConfig(
        project=ProjectConfig(name="test", data_dir=str(tmp_dir / ".n")),
        storage=StorageConfig(
            fs_cas_root=str(tmp_dir / "blobs"),
            sqlite_path=str(tmp_dir / "index.sqlite3"),
        ),
    )
    blob = FsCasStore(config.storage.fs_cas_root)
    idx = SqliteIndexStore(config.storage.sqlite_path)
    runner = AgentRunner(config, blob, idx)

    orig_build = runner._orchestrator._build_node_registry

    def patched_build(graph, *, stage_default_model_id=None, **kwargs):
        registry = orig_build(graph, stage_default_model_id=stage_default_model_id, **kwargs)
        for nid, node in registry.items():
            if hasattr(node, "set_replay_responses") and nid in _REPLAY_MAP:
                node.set_replay_responses(_REPLAY_MAP[nid])
        return registry

    runner._orchestrator._build_node_registry = patched_build  # type: ignore[method-assign]
    return runner


def test_dynamic_planner_stage_hidden_planner_node_events(
    tmp_dir: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    runner = _make_runner(tmp_dir, monkeypatch)

    handle = runner.start(RunRequest(
        objective="Create a short report from one local document.",
        metadata={
            "runbook_id": "dynamic_planner_demo_v1",
            "doc_paths": ["/tmp/a.md"],
        },
    ))
    status = runner.get_status(handle)
    assert status.state == "COMPLETED"

    events = list(runner._index.get_trace_events(handle.trace_id))

    dynamic_decisions = [
        e for e in events
        if e["kind"] == "decision"
        and e.get("payload", {}).get("description") == "Plan created (dynamic)"
    ]
    assert len(dynamic_decisions) >= 1
    payload = dynamic_decisions[0]["payload"]
    assert set(payload["nodes"]) == {"read_000", "merge_docs", "draft_report", "critic_report"}
    assert payload["planner_backend"] == "legacy_dynamic_v1"
    assert payload["planner_backend_version"] == "1"
    assert isinstance(payload["operator_catalog_hash"], str)
    assert payload["operator_catalog_hash"]

    planner_req = [
        e for e in events
        if e["kind"] == "decision"
        and e.get("payload", {}).get("description") == "Planner request envelope"
    ]
    assert planner_req

    planner_node_events = [
        e for e in events
        if e["kind"] in {"node_start", "node_end"}
        and e.get("payload", {}).get("node_id") == "plan_graph"
    ]
    assert planner_node_events == []

    for nid in ("read_000", "merge_docs", "draft_report", "critic_report"):
        assert any(
            e["kind"] == "node_start"
            and e.get("payload", {}).get("node_id") == nid
            for e in events
        )
        assert any(
            e["kind"] == "node_end"
            and e.get("payload", {}).get("node_id") == nid
            for e in events
        )
