from __future__ import annotations

import json
from pathlib import Path

import pytest

from neuronium_agent.api import AgentRunner
from neuronium_agent.config import AppConfig, ProjectConfig, StorageConfig
from neuronium_agent.storage.fs_cas import FsCasStore
from neuronium_agent.storage.sqlite_store import SqliteIndexStore
from neuronium_agent.trace.replay import ReplayProvider
from neuronium_agent.types import RunRequest


_PLANNED_GRAPH = {
    "metadata": {
        "plan_id": "plan-dynamic-generated-replay",
        "description": "Generated by planner replay",
        "version": 1,
    },
    "nodes": [
        {
            "node_id": "read_000",
            "node_type": "mcp",
            "parameters": {
                "tool_name": "fs.read_text",
                "tool_args": {"path": "/tmp/a.md", "out_key": "doc_000"},
            },
        },
        {"node_id": "merge_docs", "node_type": "aggregate", "parameters": {}},
        {"node_id": "draft_report", "node_type": "model", "parameters": {}},
        {"node_id": "critic_report", "node_type": "model", "parameters": {}},
    ],
    "edges": [
        {"source": "read_000", "target": "merge_docs", "edge_type": "data"},
        {"source": "merge_docs", "target": "draft_report", "edge_type": "data"},
        {"source": "draft_report", "target": "critic_report", "edge_type": "data"},
    ],
    "conditional_branches": [],
}

_REPLAY_MAP: dict[str, list[dict]] = {
    "plan_graph": [{
        "outputs": {"parsed": _PLANNED_GRAPH, "content": json.dumps(_PLANNED_GRAPH)},
        "quality_signals": {"tokens_used": 10},
    }],
    "read_000": [{
        "outputs": {"doc_000": "doc text", "doc_000__path": "/tmp/a.md"},
        "status": "COMPLETED",
    }],
    "merge_docs": [{"outputs": {"doc_000": "doc text"}, "status": "COMPLETED"}],
    "draft_report": [{"outputs": {"content": "report [doc_000]"}, "status": "COMPLETED"}],
    "critic_report": [{
        "outputs": {"content": json.dumps({
            "verdict": "PASS", "confidence": 0.9, "evidence": ["doc_000"], "gaps": []
        })},
        "status": "COMPLETED",
    }],
}


def _make_runner(tmp_dir: Path, monkeypatch: pytest.MonkeyPatch) -> AgentRunner:
    monkeypatch.setenv("NEURONIUM_OPENAI_API_KEY", "test-fake-key")
    config = AppConfig(
        project=ProjectConfig(name="test", data_dir=str(tmp_dir / ".n")),
        storage=StorageConfig(
            fs_cas_root=str(tmp_dir / "blobs"),
            sqlite_path=str(tmp_dir / "index.sqlite3"),
        ),
    )
    runner = AgentRunner(
        config,
        FsCasStore(config.storage.fs_cas_root),
        SqliteIndexStore(config.storage.sqlite_path),
    )
    orig_build = runner._orchestrator._build_node_registry

    def patched_build(graph):
        registry = orig_build(graph)
        for nid, node in registry.items():
            if hasattr(node, "set_replay_responses") and nid in _REPLAY_MAP:
                node.set_replay_responses(_REPLAY_MAP[nid])
        return registry

    runner._orchestrator._build_node_registry = patched_build  # type: ignore[method-assign]
    return runner


def test_strict_replay_fails_on_operator_catalog_hash_mismatch(
    tmp_dir: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    runner = _make_runner(tmp_dir, monkeypatch)
    handle = runner.start(RunRequest(
        objective="Create report",
        metadata={"runbook_id": "dynamic_planner_demo_v1"},
    ))
    assert runner.get_status(handle).state == "COMPLETED"

    class _MismatchedCatalog:
        def catalog_hash(self) -> str:
            return "mismatch-hash"

        def assert_node_allowed(self, node) -> None:  # noqa: ANN001
            return None

    runner._orchestrator._operator_catalog = _MismatchedCatalog()  # type: ignore[assignment]

    replay_handle = runner.replay(handle.trace_id)
    replay_status = runner.get_status(replay_handle)
    assert replay_status.state == "FAILED"

    events = list(runner._index.get_trace_events(replay_handle.trace_id))
    assert any(
        e["kind"] == "error"
        and "operator catalog hash mismatch" in str(e.get("payload", {}).get("error", ""))
        for e in events
    )


def test_replay_provider_supports_strict_inject_for_htn_path() -> None:
    events = [
        {
            "kind": "decision",
            "payload": {
                "description": "Planner request envelope",
                "planner_backend": "htn_recursive_v0",
                "operator_catalog_hash": "hash-htn-001",
            },
        },
        {
            "kind": "replay_data",
            "payload": {
                "node_id": "draft_report",
                "recorded_responses": [{"outputs": {"content": "draft"}}],
            },
        },
        {
            "kind": "replay_data",
            "payload": {
                "node_id": "critic_report",
                "recorded_responses": [{"outputs": {"content": "{\"verdict\":\"PASS\"}"}}],
            },
        },
    ]
    provider = ReplayProvider(events)

    class _ReplayNode:
        def __init__(self) -> None:
            self.responses: list[dict] = []

        def set_replay_responses(self, responses: list[dict]) -> None:
            self.responses = list(responses)

    draft = _ReplayNode()
    critic = _ReplayNode()
    report = provider.inject(
        {"draft_report": draft, "critic_report": critic},
        strict=True,
    )
    assert report["missing"] == []
    assert provider.latest_operator_catalog_hash() == "hash-htn-001"
    assert len(draft.responses) == 1
    assert len(critic.responses) == 1


def test_replay_provider_accumulates_multiple_replay_entries_per_node() -> None:
    events = [
        {
            "kind": "replay_data",
            "payload": {
                "node_id": "plan_node",
                "recorded_responses": [{"outputs": {"step": 1}}],
            },
        },
        {
            "kind": "replay_data",
            "payload": {
                "node_id": "plan_node",
                "recorded_responses": [{"outputs": {"step": 2}}],
            },
        },
    ]
    provider = ReplayProvider(events)

    class _ReplayNode:
        def __init__(self) -> None:
            self.responses: list[dict] = []

        def set_replay_responses(self, responses: list[dict]) -> None:
            self.responses = list(responses)

    node = _ReplayNode()
    report = provider.inject({"plan_node": node}, strict=True)
    assert report["missing"] == []
    assert len(node.responses) == 2
