from __future__ import annotations

import json
from pathlib import Path

import pytest

from neuronium_agent.api import AgentRunner
from neuronium_agent.config import AppConfig, ProjectConfig, StorageConfig
from neuronium_agent.storage.fs_cas import FsCasStore
from neuronium_agent.storage.sqlite_store import SqliteIndexStore
from neuronium_agent.types import RunRequest


_PLANNED_GRAPH = {
    "metadata": {
        "plan_id": "plan-dynamic-generated-artifacts",
        "description": "Generated by planner replay",
        "version": 1,
    },
    "nodes": [
        {"node_id": "read_000", "node_type": "mcp", "parameters": {"tool_name": "fs.read_text", "tool_args": {"path": "/tmp/a.md", "out_key": "doc_000"}}},
        {"node_id": "merge_docs", "node_type": "aggregate", "parameters": {}},
        {"node_id": "draft_report", "node_type": "model", "parameters": {}},
        {"node_id": "critic_report", "node_type": "model", "parameters": {}},
    ],
    "edges": [
        {"source": "read_000", "target": "merge_docs", "edge_type": "data"},
        {"source": "merge_docs", "target": "draft_report", "edge_type": "data"},
        {"source": "draft_report", "target": "critic_report", "edge_type": "data"},
    ],
    "conditional_branches": [],
}

_REPLAY_MAP: dict[str, list[dict]] = {
    "plan_graph": [{
        "outputs": {"parsed": _PLANNED_GRAPH, "content": json.dumps(_PLANNED_GRAPH)},
        "status": "COMPLETED",
    }],
    "read_000": [{
        "outputs": {"doc_000": "doc text", "doc_000__path": "/tmp/a.md"},
        "status": "COMPLETED",
    }],
    "merge_docs": [{"outputs": {"doc_000": "doc text"}, "status": "COMPLETED"}],
    "draft_report": [{"outputs": {"content": "report [doc_000]"}, "status": "COMPLETED"}],
    "critic_report": [{
        "outputs": {"content": json.dumps({
            "verdict": "PASS", "confidence": 0.9, "evidence": ["doc_000"], "gaps": []
        })},
        "status": "COMPLETED",
    }],
}


def _make_runner(tmp_dir: Path, monkeypatch: pytest.MonkeyPatch) -> AgentRunner:
    monkeypatch.setenv("NEURONIUM_OPENAI_API_KEY", "test-fake-key")
    config = AppConfig(
        project=ProjectConfig(name="test", data_dir=str(tmp_dir / ".n")),
        storage=StorageConfig(
            fs_cas_root=str(tmp_dir / "blobs"),
            sqlite_path=str(tmp_dir / "index.sqlite3"),
        ),
    )
    runner = AgentRunner(
        config,
        FsCasStore(config.storage.fs_cas_root),
        SqliteIndexStore(config.storage.sqlite_path),
    )
    orig_build = runner._orchestrator._build_node_registry

    def patched_build(graph, *, stage_default_model_id=None, **kwargs):
        registry = orig_build(graph, stage_default_model_id=stage_default_model_id, **kwargs)
        for nid, node in registry.items():
            if hasattr(node, "set_replay_responses") and nid in _REPLAY_MAP:
                node.set_replay_responses(_REPLAY_MAP[nid])
        return registry

    runner._orchestrator._build_node_registry = patched_build  # type: ignore[method-assign]
    return runner


def test_local_rendered_index_is_updated_after_multiple_runs(
    tmp_dir: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    runner = _make_runner(tmp_dir, monkeypatch)
    req = RunRequest(objective="Create report", metadata={"runbook_id": "dynamic_planner_demo_v1"})

    h1 = runner.start(req)
    h2 = runner.start(req)
    assert runner.get_status(h1).state == "COMPLETED"
    assert runner.get_status(h2).state == "COMPLETED"

    rendered_dir = tmp_dir / ".n" / "rendered"
    index_jsonl = rendered_dir / "index.jsonl"
    index_html = rendered_dir / "index.html"
    assert index_jsonl.exists()
    assert index_html.exists()

    rows = [line for line in index_jsonl.read_text(encoding="utf-8").splitlines() if line.strip()]
    assert len(rows) >= 2
    entries = [json.loads(line) for line in rows]
    trace_ids = {str(e["trace_id"]) for e in entries}
    assert h1.trace_id in trace_ids
    assert h2.trace_id in trace_ids

    html_files = list(rendered_dir.glob("*.html"))
    # index.html + at least one rendered run file
    assert len(html_files) >= 2
